"""Batch Document VQA package."""

def main() -> None:
    """Main entry point for batch-doc-vqa CLI."""
    print("Batch Document VQA - Available commands:")
    print("")
    print("🤖 Multi-Provider Inference:")
    print("  uv run openrouter-inference --model MODEL_NAME  # Router with provider choice")
    print("  uv run openrouter-ui                            # Interactive provider+model selection")
    print("  uv run gemini-inference --model MODEL_NAME      # Direct Google Gemini API")
    print("  uv run openai-inference --model MODEL_NAME      # Direct OpenAI API")
    print("")
    print("📊 Benchmarks & Analysis:")
    print("  uv run update-benchmarks")
    print("  uv run generate-benchmark-table")
    print("  uv run generate-pareto-plot")
    print("  uv run update-readme-section")
    print("")
    print("💡 Examples:")
    print("  uv run openrouter-inference --model z-ai/glm-4.5v")
    print("  uv run gemini-inference --model gemini-2.0-flash-exp")
    print("  uv run update-benchmarks --patterns glm qwen")
    print("")
    print("📦 Installation (optional providers):")
    print("  uv add --optional gemini    # Install Gemini dependencies")
    print("  uv add --optional openai    # Install OpenAI dependencies")
